### ISSUE TITLE
Links under Packages, Integration, and App Examples need a short description.

### ISSUE THREAD

**Issue by grabear** [grabear/awesome-rshiny#11]
- [**Link**](https://github.com/grabear/awesome-rshiny/issues/new) - Short description.

**Comment by grabear** [comment]
@ucg8j

**Comment by ucg8j** [comment]
Good idea. Happy to help out on this too.

**Comment by grabear** [comment]
Thanks for helping so much!  @ucg8j

**Comment by amrrs** [comment]
Just a suggestion. Labelling this with ```Hacktoberfest``` could get more contributors helping on this!

**Comment by grabear** [comment]
@amrrs Thanks!  I saw this the other day, but I forgot to do that.

**Comment by ucg8j** [comment]
How are we doing on this issue? The `dev-master` looks like it pretty much meets this issue.
Can we merge `dev-master` onto `master`?

**Comment by grabear** [comment]
Yea this issue can be closed, and the dev-master can be merged.  It's been a while since we've updated. @ucg8j
