### ISSUE TITLE
Add your favorite rshiny tutorials, packages, or apps!

### ISSUE THREAD

**Issue by sdhutchins** [grabear/awesome-rshiny#14]
Add your favorite rshiny tutorials, packages, or apps!
1. Fork the repository
2. Add tutorial/package/app to the readme.
3. Agree to be a contributor by telling us the name/link you want on the readme (when you submit a pr it will provide more guidelines)

**Comment by amrrs** [comment]
Oh good to see this :) So am I a contributor now?

**Comment by sdhutchins** [comment]
haha hey @grabear thoughts?

**Comment by sdhutchins** [comment]
:smirk: 

> Looks good. And yes I'll add you to the list of contributors @amrrs @sdhutchins #11

**Comment by amrrs** [comment]
Thanks to you both @grabear @sdhutchins. That's a privilege.

**Comment by grabear** [comment]
https://github.com/grabear/awesome-rshiny/commit/d86f2ff820e107d0afedbe631611901e97618aa3 @sdhutchins @amrrs @ucg8j I'm assuming this will work with forks as well?

**Comment by sdhutchins** [comment]
Yeah, I just gave it a quick test @grabear

**Comment by amrrs** [comment]
Sorry but a lame question. So for me to update the content. Should I update on my forked one and then send a pull request or update on the master? How to go about it? (Considering I'm being added a contributor)

**Comment by grabear** [comment]
@amrrs I'll add a contributing file.  but essentially yes.  you'll have to:
1. Fork.
2. Commit changes on fork.
3. Make PR and request review.
4. Merge PR.

I might make a development branch that we can all push to as well

**Comment by sdhutchins** [comment]
Going to close this out. It's being addressed by #20
