### ISSUE TITLE
Accepting Hacktoberfest PRs (Beginner-friendly)

### ISSUE THREAD

**Issue by amrrs** [grabear/awesome-rshiny#20]
## You can submit a PR with a small amount of research that improves our awesome list.  If you're confused, then please feel free to comment here!  We'll help you make your first open source contribution!  You can also open an issue, and add the _Beginner_ label.

**Comment by Domt301** [comment]
I've forked your repo. Id definitely want to end up with submitting a pull request. How can i contribute specifically?

**Comment by amrrs** [comment]
Hi, Thanks for your interest. This repo is about collecting awesome things about R `shiny`. 

You could contribute in a couple of ways:

- Can add a new shiny entry on any of our sections - like a new App Example or a new Tutorial
- Can add description to the existing entries - eg: updating description of googleViz

Feel free to let us know if you have any more questions.

**Comment by sdhutchins** [comment]
Hacktoberfest has ended. :cry:
