### ISSUE TITLE
Better Organize/Format the Tutorials section.

### ISSUE THREAD

**Issue by grabear** [grabear/awesome-rshiny#23]
The tutorials section is a bit mixed up.  Right now the titles look a bit messy.  And they need a better format.

Some of them are written articles so maybe we should have an article section too?

For the articles we could have something like this:

# Articles
* [Dean Attalli](link)
    * [_Minimized-Title_](link) **2017-10-06**:  _Short Description_
    **OR**
    *  [_Minimized-Title_](link) **2017**:  _Short Description_

This is open ended.  I'm just throwing out ideas.  We could always just keep the tutorials section and neaten it up a bit.

**Comment by sdhutchins** [comment]
I'm okay with it for the most part. I think we could delete `Blog Post` and just have the title.

For those not associated to someone specifically we could do an others section.

# Articles
* [Dean Attalli](link)
    * [Advanced Shiny](link):   _Advanced shiny tutorial on blah._
* Others
    * [Neon Data Skills](link):   _R Shiny Basics._

**Comment by grabear** [comment]
Excellent.  I like the idea of having a date in there too for reference..

So maybe:

# Articles
* [Dean Attalli](link)
    * [Advanced Shiny](link):   **2017**-_Advanced shiny tutorial on blah._
* Others
    * [Neon Data Skills](link):   **2015#**-_R Shiny Basics._

@sdhutchins  ?

**Comment by sdhutchins** [comment]
@grabear I think that works could even do the full date. There aren't that many tutorials here.


# Articles
* [Dean Attalli](link)
    * [Advanced Shiny](link):   **2017-08-17** | _Advanced shiny tutorial on blah._
* Others
    * [Neon Data Skills](link):   **2015-09-17** | _R Shiny Basics._

**Comment by grabear** [comment]
@sdhutchins  Ok so just as a general format for the new articles section:

# Articles
* [Author](link)
    * [Title](link):  **_YYYY-MM-DD_** | _Short description_

**Comment by ChrisZasa** [comment]
Hello Awesome rshiny-owner and contributor

I would like to contribute to our clean-up of your awesome r shiny ... I am a newbie on GitHub but would love to use the Hacktoberfest to get more secure working in this great environment and contributing to this community. 

Before I start to edit stuff ...  what is wanted is to update the tutorial sections title in the format you just proposed (Author, Title: YYYY-MM-DD short description) .. and change it from tutorial to article ... correct? 

Best
Chrissy
