### ISSUE TITLE
The R-shiny subreddit needs a makeover.

### ISSUE THREAD

**Issue by grabear** [grabear/awesome-rshiny#26]
[r/rstats post](https://www.reddit.com/r/rstats/comments/74p6r4/awesome_rshiny_a_curated_list_of_awesome_rshiny/)

Give it an upvote or repost if you know of a better sub-reddit.

**Comment by sdhutchins** [comment]
I reposted it to some other subreddits: [r/datascience](https://www.reddit.com/r/datascience/), [r/rprogramming](https://www.reddit.com/r/rprogramming/), [r/Rlanguage](https://www.reddit.com/r/Rlanguage/)

**Comment by grabear** [comment]
Discussion about rshiny subreddit on commit:  2d07bf673eb8f26c333aa66aea8c54e9eabde69e

**Comment by grabear** [comment]
# **More reddit discussions:**  
[r/rstats post](https://www.reddit.com/r/rstats/comments/75keyg/the_rshiny_subreddit_any_thoughts_on_giving_it_a/)
