### ISSUE TITLE
Where should I put shinyproxy?

### ISSUE THREAD

**Issue by ucg8j** [grabear/awesome-rshiny#34]
I've been playing around with [shinyproxy](shinyproxy.io) at work the last couple of weeks and written a [how-to blog](http://lukesingham.com/shiny-containers-with-shinyproxy/). I think it is a great piece of kit and should feature on this awesome list. It's a free alternative to shiny server pro, with all the benefits. However, I don't think it fits neatly under the current headings:

**Services** - currently this lists where you might deploy a shiny app, but shinyproxy itself is not a service.
**Packages** - it's not an R package
**Integrations** - it's not really an integration/api.

It is related to deployment though. So I'm wondering whether a new heading of "Deployment" with "[hosting] Services" (e.g. shinyapps.io) as a subheading and "Deployment Software" e.g. shiny server / shinyproxy as another subheading.

Happy for any and all suggestions. :)

**Comment by grabear** [comment]
@ucg8j @sdhutchins I would say:

# Services
* [R-Studio Server]()
* [Shiny-Server]()
* **[ShinyProxy]()**

You could rearrange it a bit though if you wanted to.

**Comment by grabear** [comment]
Feel free to make another heading if you want.

**Comment by sdhutchins** [comment]
I think adding a Deployment subheading would be awesome even if it is under Services, but I more or less agree with @grabear, @ucg8j.

For example:

# Services
* [R-Studio Server]()
* **Deployment**:
  * [ShinyProxy]()

**Comment by ucg8j** [comment]
Sorry for the belated response. Here's what it looks like at present with some comments as to why I've structured things differently under the 'Proposed Structure'. If you don't have major objections to the proposed structure I'll submit a PR on the dev branch over the next couple of days:

# **Current structure**...

## Deployment
* [R-Studio Server](https://www.rstudio.com/products/rstudio/download-server/)
_Does this belong on the awesome shiny list? Maybe awesome-R, but my understanding of RStudio Server is that it is more about having the IDE in a browser._
* [Shiny Server](https://github.com/rstudio/shiny-server)
_For those who want to self host_
* [ShinyApps.io](http://www.shinyapps.io/)
_PAAS_ 
* [Digital Ocean](https://www.digitalocean.com/community/tutorials/how-to-set-up-shiny-server-on-ubuntu-14-04) 
_Tutorial by @daattali on how a deploy on a VPS (digital ocean)_
* [RStudio Connect](https://www.rstudio.com/products/connect/)
_Host shiny web applications plus more features_

# **Proposed structure**...

## Deployment
### Self Hosting
* [Shiny Server](https://github.com/rstudio/shiny-server)
* [RStudio Connect](https://www.rstudio.com/products/connect/)
* [Shinyproxy](https://www.shinyproxy.io/)

### Platform As A Service (PAAS)
* [ShinyApps.io](http://www.shinyapps.io/)
* [Heruku](https://www.heroku.com) - with [buildpack scripts](https://github.com/virtualstaticvoid/heroku-buildpack-r/tree/heroku-16)

## Tutorials
* [Dean Attali: Digital Ocean Deployment](https://www.digitalocean.com/community/tutorials/how-to-set-up-shiny-server-on-ubuntu-14-04)

**Comment by sdhutchins** [comment]
I like the changes @ucg8j

**Comment by grabear** [comment]
I like what you did there too!  @ucg8j

**Comment by ucg8j** [comment]
Awesome! I'll do a PR today. Thanks for your help.

**Comment by ucg8j** [comment]
[PR submitted](https://github.com/grabear/awesome-rshiny/pull/37) :)

**Comment by jjunnior** [comment]
Will it work on Windows too?
