### ISSUE TITLE
Not sure if gglabeller could be added.

### ISSUE THREAD

**Issue by amrrs** [grabear/awesome-rshiny#58]
`gglabeller` https://github.com/AliciaSchep/gglabeller is a shiny gadget to label ggplot. Would it be appropriate to add in our list?

**Comment by sdhutchins** [comment]
@amrrs I'll look this over before the week is over.

**Comment by sdhutchins** [comment]
@amrrs I would say yes - it should be added. I'd vote for having it added to integrations. It's using integrating ggplot with shiny. It's not an app and it's not necessarily a package used to enhance shiny.

Thoughts? @ucg8j @grabear

**Comment by ucg8j** [comment]
@amrrs @sdhutchins I see what you mean, it's not the easiest decision. `gglabeller` to me seems to fall into the same category as [manipulateWidget](https://github.com/rte-antares-rpackage/manipulateWidget). 

I think what might help situations like this in the future is doing something like [awesome-R](https://github.com/qinwf/awesome-r/) where each section has a little quote defining what the sections is for e.g. 

## HTML Widgets
*Packages for interactive visualizations.*
