### ISSUE TITLE
2018 update to the R shiny list.

### ISSUE THREAD

**Issue by grabear** [grabear/awesome-rshiny#61]
I don't have any examples at the moment, but soon we need to revamp the list.  I know we could probably do some link checking and other tidying up.  But I also know that I've seen many new r-shiny applications, packages, articles, etc.  So I know we can add some items soon.

Cheers,
Rob

**Comment by amrrs** [comment]
@grabear I could see apps, packages, articles listed in your message. Should we start section by section - like a week full of new apps, next packages like that?

**Comment by grabear** [comment]
@amrrs @ucg8j @sdhutchins More to come tomorrow.  :)

**Comment by grabear** [comment]
Here are some things that we need to do:
1.  Checking current links (I'll assign that to myself)
2.  Remove items that aren't **Truly Awesome**.  There may not be any.  But we should add stuff that's just fluff.  Look for quality not quantity.
3.  Add new items.

@amrrs Feel free to do it however you wish.  If you do end up picking one of those topics, then let me know.  I'll focus on on of the others this coming Friday.

**Comment by grabear** [comment]
@dm3ll3n

**Comment by aciobanusebi** [comment]
I found that https://github.com/dreamRs/shinyWidgets helped me a lot. I guess it should be on this list?

**Comment by ucg8j** [comment]
@aciobanusebi already added on the [dev-master branch ](https://github.com/grabear/awesome-rshiny/tree/dev-master)

**Comment by grabear** [comment]
https://www.reddit.com/r/Rlanguage/comments/86nd3w/help_wanted_awesome_rshiny_list_2018_update/ I'm hoping we can get some help :smile:

**Comment by jcrodriguez1989** [comment]
I would like to propose two projects I've been working on:
shinyWYSIWYG: A Shiny What You See Is What You Get (WYSIWYG) UI editor https://github.com/jcrodriguez1989/shinyWYSIWYG
shinyParallel: Run Shiny applications in a multi-session mode https://github.com/jcrodriguez1989/shinyParallel

**Comment by sdhutchins** [comment]
Hey, @jcrodriguez1989! I'm glad you want to contribute! Please check out our [contributing](https://github.com/grabear/awesome-rshiny/blob/master/CONTRIBUTING.md) docs and make a PR.
