### ISSUE TITLE
awesome-shiny-extensions

### ISSUE THREAD

**Issue by amrrs** [grabear/awesome-rshiny#78]
Does it seem to fit anywhere? 

https://github.com/nanxstats/awesome-shiny-extensions

**Comment by grabear** [comment]
I think we could use that list to update ours to some degree tbh.  I've seen it before and it's basically our list with a different name.

**Comment by sdhutchins** [comment]
Ditto. I've also seen some other shiny stuff worth adding. There may be some apps worth posting after the Rstudio contest as well.
