### ISSUE TITLE
Site Not Rendering

### ISSUE THREAD

**Issue by sdhutchins** [grabear/awesome-rshiny#8]
I'm having an issue with the [gh-pages branch](https://github.com/grabear/awesome-rshiny/tree/gh-pages) on this repository. I created an awesome-rshiny site based on the awesome ruby site. It won't render properly on this gh-pages branch for @grabear's repository but if I fork it, it renders fine as can be seen [here](http://shauritahutchins.com/awesome-rshiny/).

Any thoughts about what the issue is?

**Comment by dpastoor** [comment]
@grabear is the github pages rendering turned on in this repo? It's not just a matter of having that branch it also needs to be activated in the repo settings

**Comment by grabear** [comment]
Yes.  @dpastoor I think @sdhutchins even has a version up on her website if I'm not mistaken.  So there must be something wrong with my setting.

**Comment by sdhutchins** [comment]
I contacted github support. The response is below. @dpastoor @grabear 

_The site isn't rendering all content because some of the content is being loaded over http when the main site is loaded over https. This is producing mixed content warnings that you can see in the browser console when opening the site._

_This doesn't happen in your fork using a custom domain because that site is loading over http, so there are no mixed content warnings._

_**You can fix this by loading the content over https when site is being loaded over https.**
I hope this helps. Let us know if you have any other questions._

**Comment by sdhutchins** [comment]
Fixed it. Changed all http to https.
https://grabear.github.io/awesome-rshiny/

**Comment by sdhutchins** [comment]
Suddenly, the site isn't rendering again.

**Comment by sdhutchins** [comment]
Okay, the site is back, but it's having a slight issue at the top of the readme.

**Comment by grabear** [comment]
What was the issue?

**Comment by sdhutchins** [comment]
Check PR #29 

The badge (due to it being on the same line as the header) was causing the header to not render in markdown.

**Comment by grabear** [comment]
Something's still weird #30. @sdhutchins

**Comment by sdhutchins** [comment]
https://grabear.github.io/awesome-rshiny/ @grabear
